Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using papuff.backoffice.Controllers.Base;
using papuff.backoffice.Models.Helpers;
using papuff.backoffice.Models.Request;
using papuff.backoffice.Models.Response;
using System;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;

namespace papuff.backoffice.Controllers {
    public class AuthController : BaseController {

        public IActionResult Login() {
            return View(new AuthRequest());
        }

        [HttpPost]
        [AllowAnonymous]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(AuthRequest request) {

            request.Password = request.Password.Encrypt();
            var user = await Post<AuthResponse>("user/auth", request);

            if (user != null) {
                var properties = new AuthenticationProperties {
                    AllowRefresh = false,
                    IsPersistent = true,
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60)
                };

                var claims = new[]{
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                        new Claim(ClaimTypes.Email, user.Email),
                        new Claim(ClaimTypes.Hash, user.Token),
                        new Claim(ClaimTypes.Name, user.Name ?? "Não Informado"),
                        new Claim(ClaimTypes.DateOfBirth, DateTime.Now.ToString()),
                        new Claim(ClaimTypes.Role, user.Type.ToString()),
                    };

                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(principal, properties);
            }

            return RedirectToAction("Index", "Home");
        }
        [Authorize]
        public async Task<IActionResult> Logout(string returnUrl) {
            ViewBag.ReturnUrl = returnUrl;
            return await SingOut();
        }

        public IActionResult Register() {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterRequest request) {

            if(ModelState.IsValid){
                await Post<dynamic>("user/single", request);

                SetMessage(Models.MessageType.Success,
                    "Bem vindo marujo, confirme seu e-mail se não quiser fugir da prancha");
            }

            return RedirectToAction(nameof(Login));
        }

        private async Task<IActionResult> SingOut() {
            if (User.Identity.IsAuthenticated)
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }

        public async Task<IActionResult> PostalCode(string value) {

            var uri = new UriBuilder("https://viacep.com.br/") {
                Path = $"ws/{value}/json",
            };

            using (HttpClient client = new HttpClient()) {
                var response = await client.GetAsync(uri.ToString());

                if (response.IsSuccessStatusCode) {
                    var obj = await response.Content.ReadAsStringAsync();
                    var result = JsonConvert.DeserializeObject<dynamic>(obj);

                    // todo
                    //stateId = estadoRepository.GetByName(result.uf)?.Id;
                    //cityId = cidadeRepository.GetByName(result.localidade)?.Id;

                    return new JsonResult(new AddressRequest {
                        PostalCode = result.cep,
                        AddressLine = result.logradouro,
                        City = result.localidade,
                        District = result.bairro,
                        StateProvince = result.uf,
                    });

                    
                }
                else
                    throw new Exception("Código postal não localizado, tente novamente.");
            }
        }
    }
}

Controllers/SiegeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using papuff.backoffice.Controllers.Base;

namespace papuff.backoffice.Controllers {

    [Authorize]
    public class SiegeController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using papuff.backoffice.Controllers.Base;
using papuff.backoffice.Models;
using papuff.backoffice.Models.Helpers;
using papuff.backoffice.Models.Request;
using papuff.backoffice.Models.Response;
using papuff.backoffice.Models.Response.Base;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace papuff.backoffice.Controllers {
    [Authorize]
    public class UserController : BaseController {

        public async Task<IActionResult> Index() {
            var user = await Get<List<UserResponse>>("user/all");
            return View(user);
        }

        #region - profile -

        public async Task<IActionResult> Profile() {
            return View(await Get<UserResponse>("user/me"));
        }

        [HttpPost]
        public async Task<IActionResult> Profile(UserResponse form, string newPass) {
            var command = (UserRequest)form;

            command.NewPassword = newPass.Encrypt();

            if (ModelState.IsValid)
                await Put<BaseResponse>("user/update", command);

            return RedirectToAction(nameof(Profile));
        }

        #endregion

        #region - general -

        public async Task<IActionResult> General() {
            return View(await Get<GeneralResponse>("general/me"));
        }

        [HttpPost]
        public async Task<IActionResult> General(GeneralResponse form) {
            var command = (GeneralRequest)form;

            if (ModelState.IsValid)
                await Post<BaseResponse>("general/create", command);

            return RedirectToAction(nameof(General));
        }

        #endregion

        #region - address -

        public async Task<IActionResult> Address() {
            return View(await Get<AddressResponse>("address/me"));
        }

        [HttpPost]
        public async Task<IActionResult> Address(AddressResponse form) {
            var command = (AddressRequest)form;

            if (ModelState.IsValid)
                await Post<BaseResponse>("address/create", command);

            return RedirectToAction(nameof(Address));
        }

        #endregion

        #region - document -

        public async Task<IActionResult> Document() {
            return View(await Get<IEnumerable<DocumentResponse>>("document/me"));
        }

        [HttpPost]
        public async Task<IActionResult> Document(string imageUri, string value, DocumentType type) {
            var command = new DocumentRequest {
                ImageUri = imageUri, Value = value, Type = type
            };

            if (ModelState.IsValid)
                await Post<BaseResponse>("document/create", command);

            return RedirectToAction(nameof(Document));
        }

        public async Task<IActionResult> DocumentDelete(string id) {

            if (ModelState.IsValid)
                await Put<BaseResponse>($"document/delete/{id}", null);

            return RedirectToAction(nameof(Document));
        }

        public async Task<IActionResult> DocumentPadLock(string id) {

            if (ModelState.IsValid)
                await Put<BaseResponse>($"document/padLock/{id}", null);

            return RedirectToAction(nameof(Document));
        }

        #endregion

        #region - wallets -

        public async Task<IActionResult> Wallet() {

            var vm = await Get<WalletResponse>("wallet/me");

            if (vm is null) {
                await Get<BaseResponse>($"wallet/single/{Me}");
                return RedirectToAction(nameof(Wallet));
            }

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Receipt(WalletResponse form) {
            var command = new ReceiptRequest {
                WalletId = form.Receipt.WalletId, DateDue = form.Receipt.DateDue,
                Account = form.Receipt.Account, Agency = form.Receipt.Agency,
            };

            if (ModelState.IsValid)
                await Post<BaseResponse>($"wallet/receipt/update", command);

            return RedirectToAction(nameof(Wallet));
        }

        [HttpPost]
        public async Task<IActionResult> Payment(string id, int dateDue, DateTime expirationDate, string document, int code, string card, PaymentType type) {
            var command = new PaymentRequest {
                Card = card, Code = code, DateDue = dateDue, Document = document, Type = type, WalletId = id, Expiration = expirationDate
            };

            await Post<BaseResponse>($"wallet/payment/create", command);

            return RedirectToAction(nameof(Wallet));
        }

        #endregion

        #region - company -

        public async Task<IActionResult> Companies() {
            return View(await Get<List<CompanyResponse>>("company/me"));
        }

        [HttpPost]
        public async Task<IActionResult> Companies(string name, string email, string cnpj, string registration, string tell, DateTime openingDate, string siteUri) {
            var command = new CompanyRequest {
                CNPJ = cnpj, Email = email, Name = name, OpeningDate = openingDate,
                Registration = registration, SiteUri = siteUri, Tell = tell
            };

            if (ModelState.IsValid)
                await Post<BaseResponse>($"company/create", command);

            return RedirectToAction(nameof(Companies));
        }

        #endregion
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http.Extensions

@{
    var loggedTime = (int)(DateTime.Now - Convert.ToDateTime(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.DateOfBirth).Value)).TotalMinutes;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>@ViewData["Title"] - Papuff BackOffice</title>
    <!-- <link rel="stylesheet" href="~/css/site.min.css" /> -->
    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
          crossorigin="anonymous"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css">
    <!-- Plugins -->
    <!-- Template CSS -->
    <link rel="stylesheet" href="~/css/components.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>
<body class="sidebar-mini">
    <div id="app">
        <div class="main-wrapper">
            <div class="navbar-bg bg-dark"></div>
            <nav class="navbar navbar-expand-lg main-navbar">
                <form class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
                        <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
                    </ul>
                    <div class="search-element">
                        <input class="form-control" type="search" placeholder="Pesquisar" aria-label="Search">
                        <button class="btn" type="submit"><i class="fas fa-search"></i></button>
                    </div>
                </form>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown dropdown-list-toggle">
                        <a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
                        <div class="dropdown-menu dropdown-list dropdown-menu-right">
                            <div class="dropdown-header">
                                Notificações
                            </div>
                            <div class="dropdown-list-content">
                                <a href="#" class="dropdown-item dropdown-item-unread">
                                    <div class="dropdown-item-desc">
                                        <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                                        <div class="time">10 Hours Ago</div>
                                    </div>
                                </a>
                                <a href="#" class="dropdown-item dropdown-item-unread">
                                    <div class="dropdown-item-desc">
                                        <b>Ujang Maman</b> has moved task <b>Fix bug footer</b> to <b>Progress</b>
                                        <div class="time">12 Hours Ago</div>
                                    </div>
                                </a>
                                <a href="#" class="dropdown-item dropdown-item-unread">
                                    <div class="dropdown-item-desc">
                                        <b>Agung Ardiansyah</b> has moved task <b>Fix bug sidebar</b> to <b>Done</b>
                                        <div class="time">12 Hours Ago</div>
                                    </div>
                                </a>
                            </div>
                            <div class="dropdown-footer text-center">
                                <a href="#">Ver Todos <i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                    </li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="../dist/img/avatar/avatar-1.png" width="30" class="rounded-circle mr-1">
                            <div class="d-sm-none d-lg-inline-block">@User.Identity.Name</div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div class="dropdown-title">Logado á <b class="text-danger">@loggedTime</b> minutos</div>
                            <a asp-controller="User" asp-action="Profile" class="dropdown-item has-icon">
                                <i class="far fa-user"></i> Perfil
                            </a>
                            <a href="features-activities.html" class="dropdown-item has-icon">
                                <i class="fas fa-bolt"></i> Atividades
                            </a>
                            <a href="features-settings.html" class="dropdown-item has-icon">
                                <i class="fas fa-cog"></i> Configurações
                            </a>
                            <div class="dropdown-divider"></div>
                            <a asp-controller="Auth" asp-route-returnUrl="@Context.Request.GetEncodedPathAndQuery()" asp-action="Logout" class="dropdown-item has-icon text-danger">
                                <i class="fas fa-sign-out-alt"></i> Logout
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="main-sidebar">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a href=".././">Papuff</a>
                    </div>
                    <div class="sidebar-brand sidebar-brand-sm">
                        <a href=".././">PP</a>
                    </div>
                    <ul class="sidebar-menu">
                        <li class="menu-header">Dashboard</li>
                        <li class="dropdown">
                            <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Dashboard</span></a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link" asp-controller="Home" asp-action="Index">Acompanhamento</a></li>
                            </ul>
                        </li>
                        <li class="menu-header">Starter</li>
                        <li class="dropdown">
                            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Aplicações</span></a>
                            <ul class="dropdown-menu">
                                <li class=active><a asp-controller="Siege" asp-action="Index" class="nav-link">Cercos</a></li>
                                <li><a class="nav-link" href="layout-transparent.html">Transparent Sidebar</a></li>
                            </ul>
                        </li>
                        <li><a class="nav-link" href="blank.html"><i class="far fa-square"></i> <span>Blank Page</span></a></li>
                    </ul>
                    <div class="p-3 mt-4 mb-4 hide-sidebar-mini">
                        <a href="documentation.html" class="btn btn-primary btn-lg btn-icon-split btn-block">
                            <i class="far fa-question-circle"></i> <div>Documentation</div>
                        </a>
                    </div>
                </aside>
            </div>

            <!-- Main Content -->
            <div class="main-content">
                <section class="section">
                    @RenderBody()
                </section>
            </div>
            <footer class="main-footer">
                <div class="footer-left">
                    Copyright © Papuff @DateTime.Now.Year <div class="bullet"></div>
                </div>
                <div class="footer-right">
                    v1.0.0
                </div>
            </footer>
        </div>
    </div>

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/tooltip.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.nicescroll.min.js"></script>
    <script src="~/js/moment.min.js"></script>
    <script src="~/js/stisla.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="~/js/custom.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>